### ISSUE TITLE
Cannot dismiss to a specific view

### ISSUE THREAD

**Issue by ivan-kolesov** [Open-Bytes/SwiftUINavigator#1]
Create a simple project with programatic navigations between main->list->detail->detail->....->detail
Try to  dismiss from any detail view to list view and nothing happen.

Here: [https://github.com/ivan-kolesov/UINavigator/blob/main/Shared/ContentView.swift#L17](url) go to list view with id: list
and here [https://github.com/ivan-kolesov/UINavigator/blob/main/Shared/DetailView.swift#L26](url) try back to list view

Tested on XCode 13.3.1 in emulator iphone 13 mini

**Comment by MalekKamel** [comment]
I have fixed the issue in version `0.4.0`.
Kindly try and report if there's an issue.
